#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: ConfigMap
apiVersion: v1
metadata:
  name: eric-esoa-dr-ui-installation-endpoints
  labels:
    app: {{ template "eric-esoa-dr-ui-installation" . }}
    chart: {{ template "eric-esoa-dr-ui-installation.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "eric-esoa-dr-ui.name" . }}
    app.kubernetes.io/version: {{ include "eric-esoa-dr-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
  # Included for DR-D1121-064
  {{- include "eric-esoa-dr-ui.annotations" .| nindent 4 }}
data:
  groupsClaim: {{ .Values.groupsClaim }}
