/**
 * States corresponding to the backend
 * Job States
 */
export enum JobStatus {
  COMPLETED = 'COMPLETED',
  DISCOVERY_INPROGRESS = 'DISCOVERY_INPROGRESS',
  DISCOVERY_FAILED = 'DISCOVERY_FAILED',
  DISCOVERED = 'DISCOVERED',
  NEW = 'NEW',
  PARTIALLY_RECONCILED = 'PARTIALLY_RECONCILED',
  RECONCILE_INPROGRESS = 'RECONCILE_INPROGRESS',
  RECONCILE_REQUESTED = 'RECONCILE_REQUESTED'
}